import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Roboto } from 'next/font/google';



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Project Milo",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // You can customize weights
});


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} min-h-screen bg-gradient-to-br from-indigo-50 to-blue-500 text-white`}>
        {/* ✅ Shared Navbar */}
        <nav className="bg-transparent shadow-md sticky top-0 z-50">
          <div className="max-w-7xl mx-auto px-4 py-4">
            <div className="flex justify-center space-x-35">

              
              <Link href="/" className="px-4 py-0.5 rounded-md font-bold text-white hover:bg-white/80 hover:text-blue-800 transition duration-200">
                Home
              </Link>

              <Link
                href="/prayer-times"
                className="px-4 py-0.5 rounded-md font-bold text-white hover:bg-white/80 hover:text-blue-800 transition duration-200"
              >
                Prayer Times
              </Link>

              <Link
                href="/calendar"
                className="px-4 py-0.5 rounded-md font-bold text-white hover:bg-white/80 hover:text-blue-800 transition duration-200"
              >
                Calendar
              </Link>
              <Link
                href="/todo-list"
                className="px-4 py-0.5 rounded-md font-bold text-white hover:bg-white/80 hover:text-blue-800 transition duration-200"
              >
                To-do
              </Link>
            </div>
          </div>
        </nav>

        {/* ✅ Page content scrolls vertically */}
        <main className="min-h-screen px-4 py-14">{children}</main>
      </body>
    </html>
  );
}
